//------------------------------------
#ifndef __basisfunctions_guasspoints__
#define __basisfunctions_guasspoints__
//------------------------------------

// Automatically generated by codegeneration/basisfunctions_gausspoints.py
//
// Generates the vectors gauss_points[gq] and gauss_weights[gq]
// - stores the points and weights of the gq-point Guass rule
// - the integration is scaled to [0,1]

// Generates the matrices BiG[dg][gq]_[e]
// - dg is the degree of the dG space
// - gq is the number of Gauss quadrature points
// - e is the edge number (0-lower, 1-right, 2-up, 3-left)
//
// - Each matrix BiG_e[i,j] stores the value of the j-th basis function
//   in the i-th Gauss quadrature point alongt the edge e, weighted
//   with corresponding Gauss weight and the inverse of the mass matrix
//   inversemass(j) * phi_j( gauss_point(i) ) * gauss_weight(i)

// Generates the matrices BiGe[dg][gq]
// - stores the value of the basis functions on the edge in
//   the Guass points along the edge
// - dg is the dG degree and gq the number of Gauss points
// - BiGe[i,j] is simply phi_j( gauss_point(i) )

//------------------------------ Gauss Quadrature

constexpr double gauss_points1[1] = { 0.5 };
constexpr double gauss_weights1[1] = { 1.0 };
constexpr double gauss_points2[2] = { 0.21132486540518713, 0.7886751345948129 };
constexpr double gauss_weights2[2] = { 0.5, 0.5 };
constexpr double gauss_points3[3] = { 0.1127016653792583, 0.5, 0.8872983346207417 };
constexpr double gauss_weights3[3] = { 0.2777777777777778, 0.4444444444444444, 0.2777777777777778 };

//------------------------------ Basis Functions in Gauss Points

static const Eigen::Matrix<double, 2, 3, Eigen::RowMajor> BiG12_0 = (Eigen::Matrix<double, 2, 3, Eigen::RowMajor>() << 0.5, -0.49999999999999994, -0.8660254037844386, 0.5, 0.49999999999999994, -0.8660254037844386).finished();

static const Eigen::Matrix<double, 2, 3, Eigen::RowMajor> BiG12_1 = (Eigen::Matrix<double, 2, 3, Eigen::RowMajor>() << 0.5, 0.8660254037844386, -0.49999999999999994, 0.5, 0.8660254037844386, 0.49999999999999994).finished();

static const Eigen::Matrix<double, 2, 3, Eigen::RowMajor> BiG12_2 = (Eigen::Matrix<double, 2, 3, Eigen::RowMajor>() << 0.5, -0.49999999999999994, 0.8660254037844386, 0.5, 0.49999999999999994, 0.8660254037844386).finished();

static const Eigen::Matrix<double, 2, 3, Eigen::RowMajor> BiG12_3 = (Eigen::Matrix<double, 2, 3, Eigen::RowMajor>() << 0.5, -0.8660254037844386, -0.49999999999999994, 0.5, -0.8660254037844386, 0.49999999999999994).finished();

static const Eigen::Matrix<double, 3, 6, Eigen::RowMajor> BiG23_0 = (Eigen::Matrix<double, 3, 6, Eigen::RowMajor>() << 0.2777777777777778, -0.37267799624996495, -0.4811252243246881, 0.24845199749997676, 0.6211299937499417, 0.6454972243679029, 0.4444444444444444, 0.0, -0.7698003589195009, -0.49690399499995325, 0.9938079899999067, -0.0, 0.2777777777777778, 0.37267799624996495, -0.4811252243246881, 0.24845199749997676, 0.6211299937499417, -0.6454972243679029).finished();

static const Eigen::Matrix<double, 3, 6, Eigen::RowMajor> BiG23_1 = (Eigen::Matrix<double, 3, 6, Eigen::RowMajor>() << 0.2777777777777778, 0.4811252243246881, -0.37267799624996495, 0.6211299937499417, 0.24845199749997676, -0.6454972243679029, 0.4444444444444444, 0.7698003589195009, 0.0, 0.9938079899999067, -0.49690399499995325, 0.0, 0.2777777777777778, 0.4811252243246881, 0.37267799624996495, 0.6211299937499417, 0.24845199749997676, 0.6454972243679029).finished();

static const Eigen::Matrix<double, 3, 6, Eigen::RowMajor> BiG23_2 = (Eigen::Matrix<double, 3, 6, Eigen::RowMajor>() << 0.2777777777777778, -0.37267799624996495, 0.4811252243246881, 0.24845199749997676, 0.6211299937499417, -0.6454972243679029, 0.4444444444444444, 0.0, 0.7698003589195009, -0.49690399499995325, 0.9938079899999067, 0.0, 0.2777777777777778, 0.37267799624996495, 0.4811252243246881, 0.24845199749997676, 0.6211299937499417, 0.6454972243679029).finished();

static const Eigen::Matrix<double, 3, 6, Eigen::RowMajor> BiG23_3 = (Eigen::Matrix<double, 3, 6, Eigen::RowMajor>() << 0.2777777777777778, -0.4811252243246881, -0.37267799624996495, 0.6211299937499417, 0.24845199749997676, 0.6454972243679029, 0.4444444444444444, -0.7698003589195009, 0.0, 0.9938079899999067, -0.49690399499995325, -0.0, 0.2777777777777778, -0.4811252243246881, 0.37267799624996495, 0.6211299937499417, 0.24845199749997676, -0.6454972243679029).finished();

static const Eigen::Matrix<double, 3, 3, Eigen::RowMajor> BiG13_0 = (Eigen::Matrix<double, 3, 3, Eigen::RowMajor>() << 0.2777777777777778, -0.37267799624996495, -0.4811252243246881, 0.4444444444444444, 0.0, -0.7698003589195009, 0.2777777777777778, 0.37267799624996495, -0.4811252243246881).finished();

static const Eigen::Matrix<double, 3, 3, Eigen::RowMajor> BiG13_1 = (Eigen::Matrix<double, 3, 3, Eigen::RowMajor>() << 0.2777777777777778, 0.4811252243246881, -0.37267799624996495, 0.4444444444444444, 0.7698003589195009, 0.0, 0.2777777777777778, 0.4811252243246881, 0.37267799624996495).finished();

static const Eigen::Matrix<double, 3, 3, Eigen::RowMajor> BiG13_2 = (Eigen::Matrix<double, 3, 3, Eigen::RowMajor>() << 0.2777777777777778, -0.37267799624996495, 0.4811252243246881, 0.4444444444444444, 0.0, 0.7698003589195009, 0.2777777777777778, 0.37267799624996495, 0.4811252243246881).finished();

static const Eigen::Matrix<double, 3, 3, Eigen::RowMajor> BiG13_3 = (Eigen::Matrix<double, 3, 3, Eigen::RowMajor>() << 0.2777777777777778, -0.4811252243246881, -0.37267799624996495, 0.4444444444444444, -0.7698003589195009, 0.0, 0.2777777777777778, -0.4811252243246881, 0.37267799624996495).finished();

//------------------------------ Edge Basis Functions in Gauss Points

static const Eigen::Matrix<double, 2, 2, Eigen::RowMajor> BiGe12 = (Eigen::Matrix<double, 2, 2, Eigen::RowMajor>() << 1.0, 1.0, -0.9999999999999999, 0.9999999999999999).finished();

static const Eigen::Matrix<double, 3, 3, Eigen::RowMajor> BiGe23 = (Eigen::Matrix<double, 3, 3, Eigen::RowMajor>() << 1.0, 1.0, 1.0, -1.3416407864998738, 0.0, 1.3416407864998738, 0.8944271909999163, -1.118033988749895, 0.8944271909999163).finished();

static const Eigen::Matrix<double, 2, 3, Eigen::RowMajor> BiGe13 = (Eigen::Matrix<double, 2, 3, Eigen::RowMajor>() << 1.0, 1.0, 1.0, -1.3416407864998738, 0.0, 1.3416407864998738).finished();

//------------------------------------
#endif
