/*!
 * @file DiagnosticOutputModule.hpp
 *
 * Generated by module_header.py
 */

#ifndef DIAGNOSTICOUTPUTMODULE_HPP
#define DIAGNOSTICOUTPUTMODULE_HPP

#include "include/ConfiguredModule.hpp"
#include "include/Module.hpp"

#include "include/IDiagnosticOutput.hpp"

namespace Module {

template <> Module<Nextsim::IDiagnosticOutput>::map Module<Nextsim::IDiagnosticOutput>::functionMap;
class DiagnosticOutputModule : public Module<Nextsim::IDiagnosticOutput> {
    struct Constructor {
        Constructor();
    };
    static Constructor ctor;
};

} /* namespace Module */

#endif /* DIAGNOSTICOUTPUTMODULE_HPP */
