var annotated_dup =
[
    [ "EnumWrap", null, [
      [ "EnumWrapper", "class_enum_wrap_1_1_enum_wrapper.html", "class_enum_wrap_1_1_enum_wrapper" ]
    ] ],
    [ "Module", null, [
      [ "DiagnosticOutputModule", "class_module_1_1_diagnostic_output_module.html", null ],
      [ "DynamicsModule", "class_module_1_1_dynamics_module.html", null ],
      [ "IFreezingPointModule", "class_module_1_1_i_freezing_point_module.html", null ],
      [ "IStructureModule", "class_module_1_1_i_structure_module.html", null ],
      [ "ITestModule", "class_module_1_1_i_test_module.html", null ],
      [ "Module", "class_module_1_1_module.html", null ]
    ] ],
    [ "Nextsim", null, [
      [ "ArgV", "class_nextsim_1_1_arg_v.html", null ],
      [ "AtmIn", "class_nextsim_1_1_atm_in.html", null ],
      [ "Chrono", "class_nextsim_1_1_chrono.html", "class_nextsim_1_1_chrono" ],
      [ "CommandLineParser", "class_nextsim_1_1_command_line_parser.html", "class_nextsim_1_1_command_line_parser" ],
      [ "CommonRestartMetadata", "class_nextsim_1_1_common_restart_metadata.html", null ],
      [ "ConfigOutput", "class_nextsim_1_1_config_output.html", "class_nextsim_1_1_config_output" ],
      [ "ConfigurationHelp", "class_nextsim_1_1_configuration_help.html", null ],
      [ "ConfigurationHelpPrinter", "class_nextsim_1_1_configuration_help_printer.html", null ],
      [ "Configurator", "class_nextsim_1_1_configurator.html", "class_nextsim_1_1_configurator" ],
      [ "Configured", "class_nextsim_1_1_configured.html", "class_nextsim_1_1_configured" ],
      [ "ConfiguredBase", "class_nextsim_1_1_configured_base.html", "class_nextsim_1_1_configured_base" ],
      [ "ConfiguredModule", "class_nextsim_1_1_configured_module.html", null ],
      [ "Counterant", "class_nextsim_1_1_counterant.html", "class_nextsim_1_1_counterant" ],
      [ "CouplEr", "class_nextsim_1_1_coupl_er.html", null ],
      [ "CouplIn", "class_nextsim_1_1_coupl_in.html", null ],
      [ "DevGrid", "class_nextsim_1_1_dev_grid.html", "class_nextsim_1_1_dev_grid" ],
      [ "DevGridIO", "class_nextsim_1_1_dev_grid_i_o.html", "class_nextsim_1_1_dev_grid_i_o" ],
      [ "DevStep", "class_nextsim_1_1_dev_step.html", "class_nextsim_1_1_dev_step" ],
      [ "DummyDynamics", "class_nextsim_1_1_dummy_dynamics.html", "class_nextsim_1_1_dummy_dynamics" ],
      [ "Duration", "class_nextsim_1_1_duration.html", null ],
      [ "Dynamics", "class_nextsim_1_1_dynamics.html", "class_nextsim_1_1_dynamics" ],
      [ "HappyExcept", "class_nextsim_1_1_happy_except.html", null ],
      [ "IceCalc", "class_nextsim_1_1_ice_calc.html", null ],
      [ "IceThermo", "class_nextsim_1_1_ice_thermo.html", null ],
      [ "IDevGridIO", "class_nextsim_1_1_i_dev_grid_i_o.html", "class_nextsim_1_1_i_dev_grid_i_o" ],
      [ "IDiagnosticOutput", "class_nextsim_1_1_i_diagnostic_output.html", "class_nextsim_1_1_i_diagnostic_output" ],
      [ "IDynamics", "class_nextsim_1_1_i_dynamics.html", "class_nextsim_1_1_i_dynamics" ],
      [ "IFreezingPoint", "class_nextsim_1_1_i_freezing_point.html", "class_nextsim_1_1_i_freezing_point" ],
      [ "IModelStep", "class_nextsim_1_1_i_model_step.html", "class_nextsim_1_1_i_model_step" ],
      [ "IStructure", "class_nextsim_1_1_i_structure.html", "class_nextsim_1_1_i_structure" ],
      [ "Iterator", "class_nextsim_1_1_iterator.html", "class_nextsim_1_1_iterator" ],
      [ "LinearFreezing", "class_nextsim_1_1_linear_freezing.html", "class_nextsim_1_1_linear_freezing" ],
      [ "Logged", "class_nextsim_1_1_logged.html", null ],
      [ "MiniModelComponent", "class_nextsim_1_1_mini_model_component.html", null ],
      [ "MissingData", "class_nextsim_1_1_missing_data.html", null ],
      [ "Model", "class_nextsim_1_1_model.html", "class_nextsim_1_1_model" ],
      [ "ModelArray", "class_nextsim_1_1_model_array.html", "class_nextsim_1_1_model_array" ],
      [ "ModelArrayRef", "class_nextsim_1_1_model_array_ref.html", "class_nextsim_1_1_model_array_ref" ],
      [ "ModelArrayRef< arrayName, MARBackingStore, RW >", "class_nextsim_1_1_model_array_ref_3_01array_name_00_01_m_a_r_backing_store_00_01_r_w_01_4.html", "class_nextsim_1_1_model_array_ref_3_01array_name_00_01_m_a_r_backing_store_00_01_r_w_01_4" ],
      [ "ModelComponent", "class_nextsim_1_1_model_component.html", "class_nextsim_1_1_model_component" ],
      [ "ModelMetadata", "class_nextsim_1_1_model_metadata.html", "class_nextsim_1_1_model_metadata" ],
      [ "ModelState", "struct_nextsim_1_1_model_state.html", null ],
      [ "Module1", "class_nextsim_1_1_module1.html", "class_nextsim_1_1_module1" ],
      [ "ModuleRequestAndSupply", "class_nextsim_1_1_module_request_and_supply.html", "class_nextsim_1_1_module_request_and_supply" ],
      [ "ModuleSemiShared", "class_nextsim_1_1_module_semi_shared.html", "class_nextsim_1_1_module_semi_shared" ],
      [ "ModuleShared", "class_nextsim_1_1_module_shared.html", "class_nextsim_1_1_module_shared" ],
      [ "ModuleSupplyAndWait", "class_nextsim_1_1_module_supply_and_wait.html", "class_nextsim_1_1_module_supply_and_wait" ],
      [ "NetcdfMetadataConfiguration", "class_nextsim_1_1_netcdf_metadata_configuration.html", "class_nextsim_1_1_netcdf_metadata_configuration" ],
      [ "NoAdditionalConfiguration", "class_nextsim_1_1_no_additional_configuration.html", null ],
      [ "NZLevels", "class_nextsim_1_1_n_z_levels.html", null ],
      [ "ParaGridIO", "class_nextsim_1_1_para_grid_i_o.html", "class_nextsim_1_1_para_grid_i_o" ],
      [ "ParametricGrid", "class_nextsim_1_1_parametric_grid.html", "class_nextsim_1_1_parametric_grid" ],
      [ "PrognosticData", "class_nextsim_1_1_prognostic_data.html", "class_nextsim_1_1_prognostic_data" ],
      [ "RectangularGrid", "class_nextsim_1_1_rectangular_grid.html", "class_nextsim_1_1_rectangular_grid" ],
      [ "RectGridIO", "class_nextsim_1_1_rect_grid_i_o.html", "class_nextsim_1_1_rect_grid_i_o" ],
      [ "ScopedTimer", "class_nextsim_1_1_scoped_timer.html", "class_nextsim_1_1_scoped_timer" ],
      [ "SimpleOutput", "class_nextsim_1_1_simple_output.html", "class_nextsim_1_1_simple_output" ],
      [ "StartStepStop", "class_nextsim_1_1_start_step_stop.html", null ],
      [ "StructureFactory", "class_nextsim_1_1_structure_factory.html", null ],
      [ "TimeOptions", "class_nextsim_1_1_time_options.html", null ],
      [ "TimePoint", "class_nextsim_1_1_time_point.html", null ],
      [ "Timer", "class_nextsim_1_1_timer.html", "class_nextsim_1_1_timer" ],
      [ "TimestepTime", "struct_nextsim_1_1_timestep_time.html", null ],
      [ "UnescoFreezing", "class_nextsim_1_1_unesco_freezing.html", "class_nextsim_1_1_unesco_freezing" ]
    ] ],
    [ "Config1", "class_config1.html", null ],
    [ "Config2", "class_config2.html", "class_config2" ],
    [ "Config3", "class_config3.html", "class_config3" ],
    [ "Impl1", "class_impl1.html", null ],
    [ "Impl2", "class_impl2.html", null ],
    [ "ITest", "class_i_test.html", null ]
];