/*!
 * @file    XiosReadWrite_test.cpp
 * @author  Joe Wallwork <jw2423@cam.ac.uk>
 * @date    02 Jan 2025
 * @brief   Tests for XIOS write method
 * @details
 * This test is designed to test the read and write methods of the C++
 * interface for XIOS.
 *
 */
#include <doctest/extensions/doctest_mpi.h>
#undef INFO

#include "StructureModule/include/ParametricGrid.hpp"
#include "include/ModelMetadata.hpp"
#include "include/NextsimModule.hpp"
#include "include/ParaGridIO.hpp"
#include "include/Xios.hpp"

#include <filesystem>

namespace Nextsim {

/*!
 * Create a formatted attribute ID.
 *
 * @param label Label to use for the attribute format
 * @param dim Spatial dimensions
 * @return "<label>_<dim>D"
 */
std::string formatId(const std::string label, const int dim)
{
    return (boost::format("%1$s_%2$1dD") % label % dim).str();
}

/*!
 * Set up the XIOS handler class for testing file reading and writing.
 *
 * The function assumes two MPI ranks.
 *
 * @param dim The number of spatial dimensions
 * @param read If true, set up for file reading test, otherwise for file writing test
 */
void setupXiosHandler(int dim, bool read)
{
    if ((dim != 2) && (dim != 3)) {
        throw std::invalid_argument("Test only implemented for 2D and 3D cases");
    }

    // Get Xios singleton instance and check it's initialized
    REQUIRE_FALSE(Xios::isNull());
    Xios* xiosHandler = Xios::getInstance();
    REQUIRE(xiosHandler->isInitialized());
    const size_t size = xiosHandler->getClientMPISize();
    REQUIRE(size == 2);
    const size_t rank = xiosHandler->getClientMPIRank();

    // Set ModelArray dimensions
    const size_t nx_glo = 4;
    const size_t ny_glo = 2;
    const size_t nx = 2;
    const size_t ny = 2;
    ModelArray::setDimension(ModelArray::Dimension::X, nx_glo, nx, 0);
    ModelArray::setDimension(ModelArray::Dimension::Y, ny_glo, ny, 0);
    if (dim == 3) {
        const size_t nz = 2;
        ModelArray::setDimension(ModelArray::Dimension::Z, nz, nz, 0);
    }

    // Create a 4x2 horizontal domain with a partition halving the x-extent
    // TODO: Set local and global domain sizes upon calling ModelArray::setDimension for X and Y
    xiosHandler->createDomain("xy_domain");
    xiosHandler->setDomainType("xy_domain", "rectilinear");
    xiosHandler->setDomainGlobalXSize("xy_domain", nx_glo);
    xiosHandler->setDomainGlobalYSize("xy_domain", ny_glo);
    xiosHandler->setDomainLocalXStart("xy_domain", 2 * rank);
    xiosHandler->setDomainLocalYStart("xy_domain", 0);
    xiosHandler->setDomainLocalXValues("xy_domain", { -1.0 + rank, -0.5 + rank });
    xiosHandler->setDomainLocalYValues("xy_domain", { -1.0, 1.0 });

    if (dim == 3) {
        // Create a vertical axis with 2 points
        // TODO: Set axis size upon calling ModelArray::setDimension for Z
        xiosHandler->createAxis("z_axis");
        xiosHandler->setAxisValues("z_axis", { 0.0, 1.0 });
    }

    // Create fields on the two grids
    // TODO: Create field along with HField
    // NOTE: The grid should be auto-generated by the Xios handler class
    const std::string fieldId = formatId("field", dim);
    xiosHandler->createField(fieldId);
    xiosHandler->setFieldOperation(fieldId, "instant");
    xiosHandler->setFieldGridRef(fieldId, formatId("grid", dim));
    xiosHandler->setFieldReadAccess(fieldId, read);
    Duration timestep = xiosHandler->getCalendarTimestep();
    xiosHandler->setFieldFreqOffset(fieldId, timestep);

    // Create an file for reading/writing of field data
    std::string fileId;
    if (read) {
        fileId = "xios_test_input";
    } else {
        fileId = "xios_test_output";
    }
    xiosHandler->createFile(fileId);
    xiosHandler->setFileType(fileId, "one_file");
    xiosHandler->setFileOutputFreq(fileId, timestep);
    if (read) {
        xiosHandler->setFileMode(fileId, "read");
        xiosHandler->setFileParAccess("xios_test_input", "collective");
    } else {
        xiosHandler->setFileMode(fileId, "write");
        xiosHandler->setFileSplitFreq(fileId, Duration("P0-0T03:00:00"));
    }
    xiosHandler->fileAddField(fileId, fieldId);

    xiosHandler->close_context_definition();
}

/*!
 * Test file reading for the Xios handler configuration in setupXiosHandler.
 *
 * @param field_A Reference to nextSIM-DG HField instance to test reading from file
 * @param fieldId ID for the field used in XIOS
 */
void readFile(HField& field_A, const std::string fieldId)
{
    // Get Xios singleton instance and verify calendar step is starting from zero
    REQUIRE_FALSE(Xios::isNull());
    Xios* xiosHandler = Xios::getInstance();
    REQUIRE(xiosHandler->getCalendarStep() == 0);

    // Check the input file exists
    REQUIRE(std::filesystem::exists("xios_test_input.nc"));

    // Create ModelMetadata instance
    ModelMetadata metadata;
    metadata.setTime(xiosHandler->getCalendarStart());

    // Simulate 4 iterations (timesteps)
    Duration timestep = xiosHandler->getCalendarTimestep();
    for (int ts = 1; ts <= 4; ts++) {
        // Update the current timestep and verify it's updated in XIOS
        metadata.incrementTime(timestep);
        REQUIRE(xiosHandler->getCalendarStep() == ts);
        // Receive data from XIOS that is read from disk
        xiosHandler->read(fieldId, field_A);
    }
}

/*!
 * TestXiosRead_2D
 *
 * This function tests the file reading functionality of the C++ interface for XIOS for fields with
 * two spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosRead_2D", 2)
{
    enableXios();

    // Create ParametricGrid and ParaGridIO instances
    Module::setImplementation<IStructure>("Nextsim::ParametricGrid");
    ParametricGrid grid;
    ParaGridIO* pio = new ParaGridIO(grid);
    grid.setIO(pio);

    // Set up Xios singleton instance
    REQUIRE(Xios::isNull());
    Xios* xiosHandler = Xios::getInstance("P0-0T01:30:00", "read_2D", "2023-03-17T17:11:00Z");
    setupXiosHandler(2, true);

    // Create a HField instance to read the data into
    HField field_2D(ModelArray::Type::H);
    field_2D.resize();

    // Verify fields are read in correctly
    readFile(field_2D, "field_2D");
    const size_t nx = xiosHandler->getDomainLocalXSize("xy_domain");
    const size_t ny = xiosHandler->getDomainLocalYSize("xy_domain");
    for (size_t j = 0; j < ny; ++j) {
        for (size_t i = 0; i < nx; ++i) {
            REQUIRE(field_2D(i, j) == doctest::Approx(i + nx * j));
        }
    }
    xiosHandler->context_finalize();
}

/*!
 * TestXiosRead_3D
 *
 * This function tests the file reading functionality of the C++ interface for XIOS for fields with
 * three spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosRead_3D", 2)
{
    enableXios();

    // Create ParametricGrid and ParaGridIO instances
    Module::setImplementation<IStructure>("Nextsim::ParametricGrid");
    ParametricGrid grid;
    ParaGridIO* pio = new ParaGridIO(grid);
    grid.setIO(pio);

    // Set up Xios singleton instance
    REQUIRE(Xios::isNull());
    Xios* xiosHandler = Xios::getInstance("P0-0T01:30:00", "read_3D", "2023-03-17T17:11:00Z");
    setupXiosHandler(3, true);

    // Create a HField instance to read the data into
    HField field_3D(ModelArray::Type::Z);
    field_3D.resize();

    // Verify fields are read in correctly
    readFile(field_3D, "field_3D");
    const size_t nx = xiosHandler->getDomainLocalXSize("xy_domain");
    const size_t ny = xiosHandler->getDomainLocalYSize("xy_domain");
    const size_t nz = xiosHandler->getAxisSize("z_axis");
    for (size_t k = 0; k < nz; ++k) {
        for (size_t j = 0; j < ny; ++j) {
            for (size_t i = 0; i < nx; ++i) {
                REQUIRE(field_3D(i, j, k) == doctest::Approx(i + nx * (j + ny * k)));
            }
        }
    }
    xiosHandler->context_finalize();
}

/*!
 * Test file writing for the Xios handler configuration in setupXiosHandler.
 *
 * @param field_A Reference to nextSIM-DG HField instance to test writing to file
 * @param fieldId ID for field in XIOS
 */
void testFileWrite(HField& field_A, const std::string fieldId)
{
    // Get Xios singleton instance and verify calendar step is starting from zero
    REQUIRE_FALSE(Xios::isNull());
    Xios* xiosHandler = Xios::getInstance();
    REQUIRE(xiosHandler->getCalendarStep() == 0);

    // Check a file with the expected name doesn't exist yet
    REQUIRE_FALSE(std::filesystem::exists("xios_test_output*.nc"));

    // Create ModelMetadata instance
    ModelMetadata metadata;
    metadata.setTime(xiosHandler->getCalendarStart());

    // Simulate 4 iterations (timesteps)
    Duration timestep = xiosHandler->getCalendarTimestep();
    for (int ts = 1; ts <= 4; ts++) {
        // Update the current timestep and verify it's updated in XIOS
        metadata.incrementTime(timestep);
        REQUIRE(xiosHandler->getCalendarStep() == ts);
        // Send data to XIOS to be written to disk
        xiosHandler->write(fieldId, field_A);
    }

    // Check the files have indeed been created then remove it
    REQUIRE(std::filesystem::exists("xios_test_output_20230317171100-20230317201059.nc"));
    REQUIRE(std::filesystem::exists("xios_test_output_20230317201100-20230317231059.nc"));
    if (xiosHandler->getClientMPIRank() == 0) {
        std::filesystem::remove("xios_test_output_20230317171100-20230317201059.nc");
        std::filesystem::remove("xios_test_output_20230317201100-20230317231059.nc");
    }

    xiosHandler->context_finalize();
}

/*!
 * TestXiosWrite_2D
 *
 * This function tests the file writing functionality of the C++ interface for XIOS for fields with
 * two spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosWrite_2D", 2)
{
    enableXios();
    Xios xios_handler("P0-0T01:30:00", "write_2D", "2023-03-17T17:11:00Z");

    // Create ParametricGrid and ParaGridIO instances
    Module::setImplementation<IStructure>("Nextsim::ParametricGrid");
    ParametricGrid grid;
    ParaGridIO* pio = new ParaGridIO(grid);
    grid.setIO(pio);

    // Set up Xios singleton instance
    REQUIRE(Xios::isNull());
    Xios* xiosHandler = Xios::getInstance("P0-0T01:30:00", "write_2D", "2023-03-17T17:11:00Z");
    setupXiosHandler(2, false);

    // Create some fake data to test writing methods
    HField field_2D(ModelArray::Type::H);
    field_2D.resize();
    const size_t nx = xiosHandler->getDomainLocalXSize("xy_domain");
    const size_t ny = xiosHandler->getDomainLocalYSize("xy_domain");
    for (size_t j = 0; j < ny; ++j) {
        for (size_t i = 0; i < nx; ++i) {
            field_2D(i, j) = 1.0 * (i + nx * j);
        }
    }

    testFileWrite(field_2D, "field_2D");
}

/*!
 * TestXiosWrite_3D
 *
 * This function tests the file writing functionality of the C++ interface for XIOS for fields with
 * three spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosWrite_3D", 2)
{
    enableXios();

    // Create ParametricGrid and ParaGridIO instances
    Module::setImplementation<IStructure>("Nextsim::ParametricGrid");
    ParametricGrid grid;
    ParaGridIO* pio = new ParaGridIO(grid);
    grid.setIO(pio);

    // Set up Xios singleton instance
    REQUIRE(Xios::isNull());
    Xios* xiosHandler = Xios::getInstance("P0-0T01:30:00", "write_3D", "2023-03-17T17:11:00Z");
    setupXiosHandler(3, false);

    // Create some fake data to test writing methods
    HField field_3D(ModelArray::Type::Z);
    field_3D.resize();
    const size_t nx = xiosHandler->getDomainLocalXSize("xy_domain");
    const size_t ny = xiosHandler->getDomainLocalYSize("xy_domain");
    const size_t nz = xiosHandler->getAxisSize("z_axis");
    for (size_t k = 0; k < nz; ++k) {
        for (size_t j = 0; j < ny; ++j) {
            for (size_t i = 0; i < nx; ++i) {
                field_3D(i, j, k) = 1.0 * (i + nx * (j + ny * k));
            }
        }
    }

    testFileWrite(field_3D, "field_3D");
}

// TODO: Consider adding 4D test cases

}
