/*!
 * @file    XiosRead_test.cpp
 * @author  Joe Wallwork <jw2423@cam.ac.uk>
 * @date    02 Jan 2025
 * @brief   Tests for XIOS read functionality
 * @details
 * This test is designed to test the file reading functionality of the C++
 * interface for XIOS.
 *
 */
#include <doctest/extensions/doctest_mpi.h>
#undef INFO

#include "StructureModule/include/ParametricGrid.hpp"
#include "include/ModelMetadata.hpp"
#include "include/NextsimModule.hpp"
#include "include/ParaGridIO.hpp"
#include "include/Xios.hpp"

#include <filesystem>

namespace Nextsim {

/*!
 * TestXiosRead
 *
 * This function tests the file reading functionality of the C++ interface for XIOS for fields with
 * two and three spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosRead", 2)
{
    enableXios();

    // Create Xios singleton instance and check it's initialized
    REQUIRE(Xios::isNull());
    Xios* xiosHandler = Xios::getInstance("P0-0T01:30:00", "test", "2023-03-17T17:11:00Z");
    REQUIRE(xiosHandler->isInitialized());
    const size_t size = xiosHandler->getClientMPISize();
    REQUIRE(size == 2);
    const size_t rank = xiosHandler->getClientMPIRank();

    // Set ModelArray dimensions
    const size_t nx_glo = 4;
    const size_t ny_glo = 2;
    const size_t nx = 2;
    const size_t ny = 2;
    const size_t nz = 2;
    ModelArray::setDimension(ModelArray::Dimension::X, nx_glo, nx, 0);
    ModelArray::setDimension(ModelArray::Dimension::Y, ny_glo, ny, 0);
    ModelArray::setDimension(ModelArray::Dimension::Z, nz, nz, 0);

    // Create a 4x2 horizontal domain with a partition halving the x-extent
    // TODO: Set local and global domain sizes upon calling ModelArray::setDimension for X and Y
    xiosHandler->createDomain("xy_domain");
    xiosHandler->setDomainType("xy_domain", "rectilinear");
    xiosHandler->setDomainGlobalXSize("xy_domain", nx_glo);
    xiosHandler->setDomainGlobalYSize("xy_domain", ny_glo);
    xiosHandler->setDomainLocalXStart("xy_domain", 2 * rank);
    xiosHandler->setDomainLocalYStart("xy_domain", 0);
    xiosHandler->setDomainLocalXValues("xy_domain", { -1.0 + rank, -0.5 + rank });
    xiosHandler->setDomainLocalYValues("xy_domain", { -1.0, 1.0 });
    xiosHandler->createAxis("z_axis");
    xiosHandler->setAxisValues("z_axis", { 0.0, 1.0 });

    // Create fields on the two grids
    // TODO: Create fields along with HField
    // NOTE: The grid should be auto-generated by the Xios handler class
    xiosHandler->createField("field_2D");
    xiosHandler->setFieldOperation("field_2D", "instant");
    xiosHandler->setFieldGridRef("field_2D", "grid_2D");
    xiosHandler->setFieldReadAccess("field_2D", true);
    Duration timestep = xiosHandler->getCalendarTimestep();
    xiosHandler->setFieldFreqOffset("field_2D", timestep);
    xiosHandler->createField("field_3D");
    xiosHandler->setFieldOperation("field_3D", "instant");
    xiosHandler->setFieldGridRef("field_3D", "grid_3D");
    xiosHandler->setFieldReadAccess("field_3D", true);
    xiosHandler->setFieldFreqOffset("field_3D", timestep);

    // Create an file for reading of field data
    std::string fileId = "xios_test_input";
    xiosHandler->createFile(fileId);
    xiosHandler->setFileType(fileId, "one_file");
    xiosHandler->setFileOutputFreq(fileId, timestep);
    xiosHandler->setFileMode(fileId, "read");
    xiosHandler->setFileParAccess(fileId, "collective");
    xiosHandler->fileAddField(fileId, "field_2D");
    xiosHandler->fileAddField(fileId, "field_3D");

    xiosHandler->close_context_definition();

    // Create HField instances to read the data into
    HField field_2D(ModelArray::Type::H);
    field_2D.resize();
    HField field_3D(ModelArray::Type::Z);
    field_3D.resize();

    // Check calendar step is zero initially
    REQUIRE(xiosHandler->getCalendarStep() == 0);

    // Check the input file exists
    REQUIRE(std::filesystem::exists("xios_test_input.nc"));

    // Create ModelMetadata instance
    ModelMetadata metadata;
    metadata.setTime(xiosHandler->getCalendarStart());

    // Simulate 4 iterations (timesteps)
    for (int ts = 1; ts <= 4; ts++) {
        // Update the current timestep and verify it's updated in XIOS
        metadata.incrementTime(timestep);
        REQUIRE(xiosHandler->getCalendarStep() == ts);
        // Receive data from XIOS that is read from disk
        xiosHandler->read("field_2D", field_2D);
        xiosHandler->read("field_3D", field_3D);
    }

    for (size_t j = 0; j < ny; ++j) {
        for (size_t i = 0; i < nx; ++i) {
            REQUIRE(field_2D(i, j) == doctest::Approx(i + nx * j));
        }
    }
    for (size_t k = 0; k < nz; ++k) {
        for (size_t j = 0; j < ny; ++j) {
            for (size_t i = 0; i < nx; ++i) {
                REQUIRE(field_3D(i, j, k) == doctest::Approx(i + nx * (j + ny * k)));
            }
        }
    }
    xiosHandler->context_finalize();
}

}
