/*!
 * @file    XiosReadWrite_test.cpp
 * @author  Joe Wallwork <jw2423@cam.ac.uk>
 * @date    10 Dec 2024
 * @brief   Tests for XIOS write method
 * @details
 * This test is designed to test the read and write methods of the C++
 * interface for XIOS.
 *
 */
#include <doctest/extensions/doctest_mpi.h>
#undef INFO

#include "StructureModule/include/ParametricGrid.hpp"
#include "include/ModelMetadata.hpp"
#include "include/NextsimModule.hpp"
#include "include/ParaGridIO.hpp"

#include <filesystem>

namespace Nextsim {

/*!
 * Create a formatted attribute ID.
 *
 * @param label Label to use for the attribute format
 * @param dim Spatial dimensions
 * @return "<label>_<dim>D"
 */
std::string formatId(const std::string label, const int dim)
{
    return (boost::format("%1$s_%2$1dD") % label % dim).str();
}

/*!
 * Set up the XIOS handler class for testing file reading and writing.
 *
 * The function assumes two MPI ranks.
 *
 * @param dim The number of spatial dimensions
 * @param read If true, set up for file reading test, otherwise for file writing test
 * @return Appropriately configured Xios handler class instance
 */
Xios setupXiosHandler(int dim, bool read)
{
    if ((dim != 2) && (dim != 3)) {
        throw std::invalid_argument("Test only implemented for 2D and 3D cases");
    }

    enableXios();

    // Create ParametricGrid and ParaGridIO instances
    Module::setImplementation<IStructure>("Nextsim::ParametricGrid");
    ParametricGrid grid;
    ParaGridIO* pio = new ParaGridIO(grid);
    grid.setIO(pio);

    // Initialize an Xios instance called xios_handler
    // TODO: Create XIOS handler along with ParaGridIO instance
    std::string label;
    if (read) {
        label = "read";
    } else {
        label = "write";
    }
    Xios xios_handler("P0-0T01:30:00", formatId(label, dim), "2023-03-17T17:11:00Z");
    REQUIRE(xios_handler.isInitialized());
    const size_t size = xios_handler.getClientMPISize();
    REQUIRE(size == 2);
    const size_t rank = xios_handler.getClientMPIRank();

    // Set ModelArray dimensions
    const size_t nx_glo = 4;
    const size_t ny_glo = 2;
    const size_t nx = 2;
    const size_t ny = 2;
    ModelArray::setDimension(ModelArray::Dimension::X, nx_glo, nx, 0);
    ModelArray::setDimension(ModelArray::Dimension::Y, ny_glo, ny, 0);
    if (dim == 3) {
        const size_t nz = 2;
        ModelArray::setDimension(ModelArray::Dimension::Z, nz, nz, 0);
    }

    // Create a 4x2 horizontal domain with a partition halving the x-extent
    // TODO: Set local and global domain sizes upon calling ModelArray::setDimension for X and Y
    xios_handler.createDomain("xy_domain");
    xios_handler.setDomainType("xy_domain", "rectilinear");
    xios_handler.setDomainGlobalXSize("xy_domain", nx_glo);
    xios_handler.setDomainGlobalYSize("xy_domain", ny_glo);
    xios_handler.setDomainLocalXStart("xy_domain", 2 * rank);
    xios_handler.setDomainLocalYStart("xy_domain", 0);
    xios_handler.setDomainLocalXValues("xy_domain", { -1.0 + rank, -0.5 + rank });
    xios_handler.setDomainLocalYValues("xy_domain", { -1.0, 1.0 });

    if (dim == 3) {
        // Create a vertical axis with 2 points
        // TODO: Set axis size upon calling ModelArray::setDimension for Z
        xios_handler.createAxis("z_axis");
        xios_handler.setAxisValues("z_axis", { 0.0, 1.0 });
    }

    // Create fields on the two grids
    // TODO: Create field along with HField
    // NOTE: The grid should be auto-generated by the Xios handler class
    const std::string fieldId = formatId("field", dim);
    xios_handler.createField(fieldId);
    xios_handler.setFieldOperation(fieldId, "instant");
    xios_handler.setFieldGridRef(fieldId, formatId("grid", dim));
    xios_handler.setFieldReadAccess(fieldId, read);
    Duration timestep = xios_handler.getCalendarTimestep();
    xios_handler.setFieldFreqOffset(fieldId, timestep);

    // Create an file for reading/writing of field data
    std::string fileId;
    if (read) {
        fileId = "xios_test_input";
    } else {
        fileId = "xios_test_output";
    }
    xios_handler.createFile(fileId);
    xios_handler.setFileType(fileId, "one_file");
    xios_handler.setFileOutputFreq(fileId, timestep);
    if (read) {
        xios_handler.setFileMode(fileId, "read");
        xios_handler.setFileParAccess("xios_test_input", "collective");
    } else {
        xios_handler.setFileMode(fileId, "write");
        xios_handler.setFileSplitFreq(fileId, Duration("P0-0T03:00:00"));
    }
    xios_handler.fileAddField(fileId, fieldId);

    xios_handler.close_context_definition();
    return xios_handler;
}

/*!
 * Test file reading for the Xios handler configuration in setupXiosHandler.
 *
 * @param xios_handler Pointer to Xios handler class instance configured using setupXiosHandler
 * @param field_A Reference to nextSIM-DG HField instance to test reading from file
 */
void readFile(Xios* xios_handler, HField& field_A, const std::string fieldId)
{
    // Verify calendar step is starting from zero
    REQUIRE(xios_handler->getCalendarStep() == 0);

    // Check the input file exists
    REQUIRE(std::filesystem::exists("xios_test_input.nc"));

    // Create ModelMetadata instance
    ModelMetadata metadata;
    metadata.setXiosHandler(xios_handler);
    metadata.setTime(xios_handler->getCalendarStart());

    // FIXME: Why is timestep undefined?
    xios_handler->setCalendarTimestep(Duration("P0-0T01:30:00")); // Shouldn't be necessary
    Duration timestep = xios_handler->getCalendarTimestep();

    // Simulate 4 iterations (timesteps)
    for (int ts = 1; ts <= 4; ts++) {
        // Update the current timestep and verify it's updated in XIOS
        metadata.incrementTime(timestep);
        REQUIRE(xios_handler->getCalendarStep() == ts);
        // Receive data from XIOS that is read from disk
        xios_handler->read(fieldId, field_A);
    }
}

/*!
 * Utility for checking that two double values are approximately equal.
 *
 * Without this (i.e., if it's inlined below) the first test passes but the second one fails. The
 * same is true with any REQUIRE call.
 *
 * @param val1 the first double
 * @param val2 the second double
 */
void assertIsClose(double val1, double val2) { REQUIRE(val1 == doctest::Approx(val2)); }

/*!
 * TestXiosRead_2D
 *
 * This function tests the file reading functionality of the C++ interface for XIOS for fields with
 * two spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosRead_2D", 2)
{
    Xios xios_handler = setupXiosHandler(2, true);

    // Create a HField instance to read the data into
    HField field_2D(ModelArray::Type::H);
    field_2D.resize();

    // Verify fields are read in correctly
    readFile(&xios_handler, field_2D, "field_2D");
    const size_t nx = xios_handler.getDomainLocalXSize("xy_domain");
    const size_t ny = xios_handler.getDomainLocalYSize("xy_domain");
    for (size_t j = 0; j < ny; ++j) {
        for (size_t i = 0; i < nx; ++i) {
            assertIsClose(field_2D(i, j), i + nx * j);
        }
    }
    xios_handler.context_finalize();
}

/*!
 * TestXiosRead_3D
 *
 * This function tests the file reading functionality of the C++ interface for XIOS for fields with
 * three spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosRead_3D", 2)
{
    Xios xios_handler = setupXiosHandler(3, true);

    // Create a HField instance to read the data into
    HField field_3D(ModelArray::Type::Z);
    field_3D.resize();

    // Verify fields are read in correctly
    readFile(&xios_handler, field_3D, "field_3D");
    const size_t nx = xios_handler.getDomainLocalXSize("xy_domain");
    const size_t ny = xios_handler.getDomainLocalYSize("xy_domain");
    const size_t nz = xios_handler.getAxisSize("z_axis");
    for (size_t k = 0; k < nz; ++k) {
        for (size_t j = 0; j < ny; ++j) {
            for (size_t i = 0; i < nx; ++i) {
                assertIsClose(field_3D(i, j, k), i + nx * (j + ny * k));
            }
        }
    }
    xios_handler.context_finalize();
}

/*!
 * Test file writing for the Xios handler configuration in setupXiosHandler.
 *
 * @param xios_handler Pointer to Xios handler class instance configured using setupXiosHandler
 * @param field_A Reference to nextSIM-DG HField instance to test writing to file
 */
void testFileWrite(Xios* xios_handler, HField& field_A, const std::string fieldId)
{
    // Verify calendar step is starting from zero
    REQUIRE(xios_handler->getCalendarStep() == 0);

    // Check a file with the expected name doesn't exist yet
    REQUIRE_FALSE(std::filesystem::exists("xios_test_output*.nc"));

    // Create ModelMetadata instance
    ModelMetadata metadata;
    metadata.setXiosHandler(xios_handler);
    metadata.setTime(xios_handler->getCalendarStart());

    // FIXME: Why is timestep undefined?
    xios_handler->setCalendarTimestep(Duration("P0-0T01:30:00")); // Shouldn't be necessary
    Duration timestep = xios_handler->getCalendarTimestep();

    // Simulate 4 iterations (timesteps)
    for (int ts = 1; ts <= 4; ts++) {
        // Update the current timestep and verify it's updated in XIOS
        metadata.incrementTime(timestep);
        REQUIRE(xios_handler->getCalendarStep() == ts);
        // Send data to XIOS to be written to disk
        xios_handler->write(fieldId, field_A);
    }

    // Check the files have indeed been created then remove it
    REQUIRE(std::filesystem::exists("xios_test_output_20230317171100-20230317201059.nc"));
    REQUIRE(std::filesystem::exists("xios_test_output_20230317201100-20230317231059.nc"));
    if (xios_handler->getClientMPIRank() == 0) {
        std::filesystem::remove("xios_test_output_20230317171100-20230317201059.nc");
        std::filesystem::remove("xios_test_output_20230317201100-20230317231059.nc");
    }

    xios_handler->context_finalize();
}

/*!
 * TestXiosWrite_2D
 *
 * This function tests the file writing functionality of the C++ interface for XIOS for fields with
 * two spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosWrite_2D", 2)
{
    Xios xios_handler = setupXiosHandler(2, false);

    // Create some fake data to test writing methods
    HField field_2D(ModelArray::Type::H);
    field_2D.resize();
    const size_t nx = xios_handler.getDomainLocalXSize("xy_domain");
    const size_t ny = xios_handler.getDomainLocalYSize("xy_domain");
    for (size_t j = 0; j < ny; ++j) {
        for (size_t i = 0; i < nx; ++i) {
            field_2D(i, j) = 1.0 * (i + nx * j);
        }
    }

    testFileWrite(&xios_handler, field_2D, "field_2D");
}

/*!
 * TestXiosWrite_3D
 *
 * This function tests the file writing functionality of the C++ interface for XIOS for fields with
 * three spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosWrite_3D", 2)
{
    Xios xios_handler = setupXiosHandler(3, false);

    // Create some fake data to test writing methods
    HField field_3D(ModelArray::Type::Z);
    field_3D.resize();
    const size_t nx = xios_handler.getDomainLocalXSize("xy_domain");
    const size_t ny = xios_handler.getDomainLocalYSize("xy_domain");
    const size_t nz = xios_handler.getAxisSize("z_axis");
    for (size_t k = 0; k < nz; ++k) {
        for (size_t j = 0; j < ny; ++j) {
            for (size_t i = 0; i < nx; ++i) {
                field_3D(i, j, k) = 1.0 * (i + nx * (j + ny * k));
            }
        }
    }

    testFileWrite(&xios_handler, field_3D, "field_3D");
}

// TODO: Consider adding 4D test cases

}
