/*!
 * @file IIceAlbedo.hpp
 *
 * Generated by module_header.py
 */

#ifndef ICEALBEDOMODULE_HPP
#define ICEALBEDOMODULE_HPP

#include "include/ConfiguredModule.hpp"
#include "include/Module.hpp"

#include "IIceAlbedo.hpp"

namespace Module {

template <> Module<Nextsim::IIceAlbedo>::map Module<Nextsim::IIceAlbedo>::functionMap;
class IceAlbedoModule : public Module<Nextsim::IIceAlbedo> {
    struct Constructor {
        Constructor();
    };
    static Constructor ctor;
};

} /* namespace Module */

#endif /* ICEALBEDOMODULE_HPP */
