FROM alpine:latest

USER root

RUN apk add --no-cache \
    bash \
    build-base \
    python3-dev \
    netcdf-cxx4-dev \
    boost-dev \
    eigen-dev \ 
    cmake \
    hdf5-dev \
    py3-pip

RUN pip install --break-system-packages netcdf4 

WORKDIR /home/nextsim
COPY . /home/nextsim

RUN rm -r build
RUN mkdir -p /home/nextsim/build 
WORKDIR /home/nextsim/build 
RUN cmake -B/home/nextsim/build  -H/home/nextsim/ >&2
RUN make -j4 >&2

WORKDIR /home/nextsim/run
RUN ln -sf /home/nextsim/build/nextsim

CMD  ["/bin/sh"]
