FROM sphinxdoc/sphinx

WORKDIR /docs
ADD requirements.txt /docs
ADD scripts/build-docs.sh /
ADD scripts/doxygen_prep.sh /
RUN pip3 install -r requirements.txt

RUN apt-get update \
 && apt-get install --no-install-recommends --yes \
      doxygen \
 && apt-get autoremove \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["bash", "/build-docs.sh"]
