FROM ghcr.io/nextsimhub/nextsimdg-base:latest

WORKDIR /nextsimdg/build

# Download and install XIOS
COPY install-xios.sh .
RUN . /opt/spack-environment/activate.sh && bash install-xios.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/bin/bash" ]
