FROM ghcr.io/nextsimhub/nextsimdg-dev-env:latest

RUN git clone https://github.com/nextsimhub/nextsimdg.git /nextsimdg

WORKDIR /nextsimdg

ARG mpi=OFF
ARG xios=OFF
ARG jobs=1

RUN . /opt/spack-environment/activate.sh && cmake -B build -S . -DENABLE_MPI=$mpi -DENABLE_XIOS=$xios -Dxios_DIR=/xios -DCMAKE_BUILD_TYPE=Release && cmake --build build -j $jobs

WORKDIR /nextsimdg/run
RUN ln -sf /nextsimdg/build/nextsim

ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/bin/bash" ]
