default_str = "DEFAULT"
module_file_str = "module.cfg"
module_section_str = "module"
module_file_prefix = "module"
header_suffix = "hpp"
source_suffix = "cpp"
name_str = "name"
file_prefix_str = "file_prefix"
interface_prefix_str = "interface_prefix"
description_str = "description"
has_help_str = "has_help"
is_default_str = "is_default"
file_encoding = "utf-8"
true_str = "true"

# Variable names for the dict of common strings
class_name = "class_name"
module_class_name = "module_class_name"
