/*!
 * @file OceanBoundaryModule.hpp
 *
 * Generated by module_header.py
 */

#ifndef OCEANBOUNDARYMODULE_HPP
#define OCEANBOUNDARYMODULE_HPP

#include "include/ConfiguredModule.hpp"
#include "include/Module.hpp"

#include "IOceanBoundary.hpp"

namespace Module {

template <> Module<Nextsim::IOceanBoundary>::map Module<Nextsim::IOceanBoundary>::functionMap;
class OceanBoundaryModule : public Module<Nextsim::IOceanBoundary> {
    struct Constructor {
        Constructor();
    };
    static Constructor ctor;
};

} /* namespace Module */

#endif /* OCEANBOUNDARYMODULE_HPP */
