#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Code generation for paramtric mesh using Q1 mapping.

@author  Thomas Richter <thomas.richter@ovgu.de>
"""

import basisfunctions as bf
import gaussquadrature as gq


# q1 basis functions on [0,1] x [0,1]
#
# 2 -- 3
# |    |
# 0 -- 1
#
def q1basis(i, x, y):
    if i == 0:
        return (1.0 - x) * (1.0 - y)
    elif i == 1:
        return x * (1.0 - y)
    elif i == 2:
        return (1.0 - x) * y
    elif i == 3:
        return x * y
    msg = "q1 basis only for i=0,1,2,3"
    raise AssertionError(msg)


def dx_q1basis(i, y):
    if i == 0:
        return -(1.0 - y)
    elif i == 1:
        return 1.0 - y
    elif i == 2:
        return -y
    elif i == 3:
        return y
    msg = "q1 basis only for i=0,1,2,3"
    raise AssertionError(msg)


def dy_q1basis(i, x):
    if i == 0:
        return -(1.0 - x)
    elif i == 1:
        return -x
    elif i == 2:
        return 1.0 - x
    elif i == 3:
        return x
    msg = "q1 basis only for i=0,1,2,3"
    raise AssertionError(msg)


## q1 basis functions in the Gauss-Points
## Generates Matrix CG_Q1_[Q]_{dtype}
## where Q is the no of guass points in each direction
## It is a 4 - Q^2 - Matrix
def cg_q1(g, dtype):
    if g > 1:
        print(
            "static const Eigen::Matrix<{0}, 4, {1}, Eigen::RowMajor> CG_Q1_{2}_{3} =".format(
                dtype, g * g, g, dtype
            )
        )
        print(
            "\t(Eigen::Matrix<{0}, 4, {1}, Eigen::RowMajor>() <<".format(dtype, g * g)
        )

    else:
        print(
            "static const Eigen::Matrix<{0}, 4, {1}> CG_Q1_{2}_{3} =".format(
                dtype, g * g, g, dtype
            )
        )
        print("\t(Eigen::Matrix<{0}, 4, {1}>() <<".format(dtype, g * g))
    print("\t", end=" ")
    for i in range(4):
        for gy in range(g):
            for gx in range(g):
                print(
                    q1basis(i, gq.gausspoints[g - 1, gx], gq.gausspoints[g - 1, gy]),
                    sep=",",
                    end="",
                )

                if gx < g - 1 or gy < g - 1 or i < 3:
                    print(", ", end="")
                else:
                    print(").finished();")
    print("")


## x- and y-derivative of the q1 basis functions in the Gauss-Points
## Generates Matrices CG_Q1x_[Q]_{dtype} and CG_Q1y_[Q]_{dtype}
## where Q is the no of guass points in each direction
## It is a 4 - Q^2
def cg_q1grad(g, dtype):
    if g > 1:
        print(
            "static const Eigen::Matrix<{0}, 4, {1}, Eigen::RowMajor> CG_Q1x_{2}_{3} =".format(
                dtype, g * g, g, dtype
            )
        )
        print(
            "\t(Eigen::Matrix<{0}, 4, {1}, Eigen::RowMajor>() <<".format(dtype, g * g)
        )

    else:
        print(
            "static const Eigen::Matrix<{0}, 4, {1}> CG_Q1x_{2}_{3} =".format(
                dtype, g * g, g, dtype
            )
        )
        print("\t(Eigen::Matrix<{0}, 4, {1}>() <<".format(dtype, g * g))
    print("\t", end=" ")
    for i in range(4):
        for gy in range(g):
            for gx in range(g):
                print(dx_q1basis(i, gq.gausspoints[g - 1, gy]), sep=",", end="")

                if gx < g - 1 or gy < g - 1 or i < 3:
                    print(", ", end="")
                else:
                    print(").finished();")
    print("")

    if g > 1:
        print(
            "static const Eigen::Matrix<{0}, 4, {1}, Eigen::RowMajor> CG_Q1y_{2}_{3} =".format(
                dtype, g * g, g, dtype
            )
        )
        print(
            "\t(Eigen::Matrix<{0}, 4, {1}, Eigen::RowMajor>() <<".format(dtype, g * g)
        )
    else:
        print(
            "static const Eigen::Matrix<{0}, 4, {1}> CG_Q1y_{2}_{3} =".format(
                dtype, g * g, g, dtype
            )
        )
        print("\t(Eigen::Matrix<{0}, 4, {1}>() <<".format(dtype, g * g))
    print("\t", end=" ")
    for i in range(4):
        for gy in range(g):
            for gx in range(g):
                print(dy_q1basis(i, gq.gausspoints[g - 1, gx]), sep=",", end="")

                if gx < g - 1 or gy < g - 1 or i < 3:
                    print(", ", end="")
                else:
                    print(").finished();")
    print("")


#################
include_guard = "__CODEGENERATIONPARAMETRICMESH_HPP"

print(f"#ifndef {include_guard}")
print(f"#define {include_guard}")
print("\n")
print("// Automatically generated by codegeneration/codeGenerationParametricMesh.py")
print("")

print('#include "NextsimDynamics.hpp"')
print("\nnamespace Nextsim {")
print("")

## CG_Q1[0-3]_GRAD_[1-3]
# Gradient of the Q1 test functions for mapping in the Gauss points
print(
    "//CG_Q1_[i]_GRAD_[Q] stores the gradient of the Q1 basis fucntions in the Gauss points on the unit element"
)
print(
    "//                  These values are e.g. required to compute the Jacobian of the mapping"
)

for q in [1, 2, 3, 4]:
    for dtype in ["float", "double"]:
        cg_q1grad(q, dtype)

## CG_Q1_[1-3]
# Gradient of the Q1 test functions for mapping in the Gauss points
print(
    "//CG_Q1_[Q] stores the 4 Q1 basis fucntions in the Gauss points on the unit element"
)
for q in [1, 2, 3, 4]:
    for dtype in ["float", "double"]:
        cg_q1(q, dtype)

print("\n} /* namespace Nextsim */\n")
print(f"\n#endif /* {include_guard} */")
