# Workflow for compiling nextSIM-DG and running the tests under various configurations
name: Test suite

on:
  # if you wish to skip running CI please don't change this section, instead
  # prefix the following notation in the title of your commit message e.g.,
  #
  # [skip ci] my commit message
  #
  # For more information, please read the GitHub
  # [documentation](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs)
  #
  # Note: You will not be able to merge into develop or main without running CI. To run CI either:
  # - edit the last commit message using `git commit --amend` and remove the tag "[skip ci]" or,
  # - create a new commit without a "[skip ci]" tag

  # Trigger the workflow upon merging into main or develop
  push:
    branches: [ main, develop ]

  # Trigger the workflow whenever commits are pushed to an open PR that changes one of the file types listed
  pull_request:
    paths:
      - '.github/workflows/test_suite.yml'
      - '**.cdl'
      - '**.cfg'
      - '**.cpp'
      - '**.hpp'
      - '**.py'
      - '**.sh'
      - '**.xml'
      - '**CMakeLists.txt'

  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

# Restrict default permissions
permissions: {}

# Cancel running jobs if new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  # MPI tests on latest Ubuntu OS with XIOS support
  test-ubuntu-mpi-xios:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/nextsimhub/nextsimdg-dev-env:latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Python installs
      run: |
        apt -y update
        apt install -y python3-venv gdb
        python3 -m venv ~/nextsim
        . $HOME/nextsim/bin/activate
        pip install jinja2 mdb-debugger

    - name: build domain_decomp
      run: |
        . /opt/spack-environment/activate.sh
        git config --global --add safe.directory /__w/nextsimdg/nextsimdg
        git submodule init
        git submodule update
        cd domain_decomp
        cmake -G "Unix Makefiles" -Bbuild -S.
        cmake --build build --config Release

    - name: build and compile with XIOS and MPI
      run: |
        # set environment variables for MPI tests to run in docker container
        export OMPI_ALLOW_RUN_AS_ROOT=1
        export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
        export OMPI_MCA_rmaps_base_oversubscribe=1
        . /opt/spack-environment/activate.sh
        . $HOME/nextsim/bin/activate
        # provide path to domain_decomp binary
        export PATH="${PATH}:${PWD}/domain_decomp/build"
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Debug \
              -DENABLE_MPI=ON \
              -Dxios_DIR="/xios" \
              -DENABLE_XIOS=ON \
              -DCMAKE_CXX_COMPILER="$(which mpic++)" ..
        make -j 4

    # tmate can be used to get an interactive ssh session to the github runner
    # for debugging actions. See
    # [here](https://github.com/mxschmitt/action-tmate) for more information.
    # uncomment these lines to debug mac build
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
